language: python
dist: xenial
python:
    - "3.7.3"

install:
    - pip install -r requirements.txt

script:
    - git clone https://github.com/mseg-dataset/mseg-api.git
    - cd mseg-api
    - sed -i '12s/.*/MSEG_DST_DIR="\/dummy\/path"/' mseg/utils/dataset_config.py
    - pip install -e .
    - cd ..
    - pip install -e .
    - pytest tests/
    
notifications:
    email:
        recipients:
            - johnwlambert@gmail.com
        on_success: change
        on_failure: change